# This is the "main" Snakefile, from which all subtasks are launched. 
# The config file is read in, and the "localrules" line specifies which rules
# should not be run on the cluster (because they don't need that much resources)
# The rule "all" is essentially the master rule, in which all final output
# files are specified (as input for it, hence there's no output specified)
# the lines that start with "include" call .smk files for specific tasks (otherwise)
# the main Snakemake file would get too long.

import re

configfile: "config.yml"
localrules: all, index_bam, index_reference, parse_json, summarize_fastq_stats, fastq_stats, merge_trimmed, retain_list


def output_files():
    if 'max_missingness_individual' in config and config["max_missingness_individual"] is not None:
        out = [f'{config["vcf_dir"]}/genome.IF-GF-MM2-OG-RM.vcf.gz',
               f'{config["vcf_dir"]}/genome.IF-GF-MM2-OG-RM.vcf.gz.csi']
    else:
        out = [f"{config['vcf_dir']}/sample.stats"]
    return out + output_files_qc()

def output_files_qc():
    return ["results/fastq_stats/runs_fastq_summary"]

rule all:
    input:
        output_files()

rule fastq_stats:
    input:
        "results/fastq_stats/runs_fastq_summary"

include: "rules/scripts.smk"

include: "rules/read_processing.smk"

include: "rules/read_mapping.smk"

include: "rules/call.smk"

include: "rules/filter.smk"

include: "rules/consensus.smk"

include: "rules/index.smk"
