genome: "data/genome.fasta"
bam_dir: "data/bam"
fastq_trimmed_dir: "data/fastq_trimmed"
raw_fastq_dir: "data/raw_fastq"
vcf_dir: "data/vcf"
chromosome_file: "data/chromosomes.txt"
read_name_pattern: "{id}_R{read}_001.fastq.gz"
individual_file: "data/individuals.txt"
adapters: "$HOME/mamba/envs/variant-calling/opt/bbmap-39.01-1/resources/adapters.fa"
optical_dup_dist: 2500
min_depth: 4