name: variant-calling
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python
  - bioconda::snakemake
  - bioconda::samtools
  - bioconda::bwa-mem2
  - bioconda::bcftools
  - bioconda::bbmap
  - bioconda::snakemake-executor-plugin-slurm
  - datamash
  - bioconda::bedtools