name: variant-calling
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python
  - snakemake
  - samtools
  - bwa-mem2
  - conda-forge::gsl==2.7
  - bcftools
  - bbmap
  - snakemake-executor-plugin-slurm
  - datamash