name: variant-calling
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python
  - bioconda::samtools
  - bioconda::bwa-mem2
  - bioconda::bcftools
  - bioconda::bbmap==39.06
  - bioconda::fastp
  - datamash
  - bioconda::bedtools
  - pip
  - pip:
    - snakemake
    - snakemake-executor-plugin-slurm
    - matplotlib