name: variant-calling
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python
  - snakemake
  - samtools
  - bwa-mem2
  - bcftools
  - bbmap
  - snakemake-executor-plugin-slurm
  - datamash
  - bedtools
  
