__use_yte__: true

datasets:
  sample_stats:
    path: ?input.table
    separator: "\t"
  
views:
  sample_stats:
    dataset: sample_stats
    render-table:
      columns:
        proportion_Missing:
          plot:
            heatmap:
              type: quantitative
              color-scheme: "viridis"